name: event-planner-prod

services:
  web:
    container_name: event_planner_prod_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_ENV=production
    depends_on:
      - db
      - redis
    restart: always

  db:
    container_name: event_planner_prod_db
    image: postgres:15
    env_file:
      - .env
    volumes:
      - event_planner_pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    container_name: event_planner_prod_redis
    image: redis:7-alpine
    restart: always

  celery:
    container_name: event_planner_prod_celery
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config worker -l info
    env_file:
      - .env
    environment:
      - DJANGO_ENV=production
    depends_on:
      - redis
      - db
    restart: always

  celery-beat:
    container_name: event_planner_prod_beat
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config beat -l info
    env_file:
      - .env
    environment:
      - DJANGO_ENV=production
    depends_on:
      - redis
    restart: always

volumes:
  event_planner_pgdata:
