name: event-planner

services:
  web:
    container_name: event_planner_web
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "6000:8000"
    environment:
      - DJANGO_ENV=development
      - DEBUG=True
      - SECRET_KEY=dev-secret-key-change-in-production
      - DB_HOST=db
      - DB_NAME=event_planner
      - DB_USER=event_planner
      - DB_PASSWORD=event_planner
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - FRONTEND_URL=http://localhost:6000
      - CORS_ALLOWED_ORIGINS=http://localhost:6000,http://127.0.0.1:6000
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  db:
    container_name: event_planner_db
    image: postgres:15
    environment:
      POSTGRES_DB: event_planner
      POSTGRES_USER: event_planner
      POSTGRES_PASSWORD: event_planner
    volumes:
      - event_planner_pgdata:/var/lib/postgresql/data
    ports:
      - "6543:5432"

  redis:
    container_name: event_planner_redis
    image: redis:7-alpine
    ports:
      - "6380:6379"

  celery:
    container_name: event_planner_celery
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery -A config worker -l info
    environment:
      - DJANGO_ENV=development
      - DEBUG=True
      - SECRET_KEY=dev-secret-key-change-in-production
      - DB_HOST=db
      - DB_NAME=event_planner
      - DB_USER=event_planner
      - DB_PASSWORD=event_planner
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - FRONTEND_URL=http://localhost:6000
    depends_on:
      - redis
      - db
    volumes:
      - .:/app

  celery-beat:
    container_name: event_planner_beat
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery -A config beat -l info
    environment:
      - DJANGO_ENV=development
      - DEBUG=True
      - SECRET_KEY=dev-secret-key-change-in-production
      - DB_HOST=db
      - DB_NAME=event_planner
      - DB_USER=event_planner
      - DB_PASSWORD=event_planner
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - FRONTEND_URL=http://localhost:6000
    depends_on:
      - redis

volumes:
  event_planner_pgdata:
