-- Event Planner app tables (PostgreSQL).
-- Apply Django contrib / JWT / celery-beat migrations first, then this file
-- if you are not using `python manage.py migrate`.
-- Datetimes are timestamptz (UTC). Do not run this against a live DB from CI.

BEGIN;

CREATE TABLE businesses_business (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    name varchar(200) NOT NULL,
    slug varchar(200) NOT NULL UNIQUE,
    business_type varchar(50) NOT NULL,
    logo varchar(100) NULL,
    description text NOT NULL,
    email varchar(254) NOT NULL,
    phone varchar(20) NOT NULL,
    address text NOT NULL,
    website varchar(200) NOT NULL,
    settings jsonb NOT NULL,
    is_active boolean NOT NULL
);

CREATE TABLE accounts_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password varchar(128) NOT NULL,
    last_login timestamptz NULL,
    is_superuser boolean NOT NULL,
    username varchar(150) NOT NULL UNIQUE,
    first_name varchar(150) NOT NULL,
    last_name varchar(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamptz NOT NULL,
    email varchar(254) NOT NULL UNIQUE,
    phone varchar(20) NOT NULL,
    timezone varchar(50) NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    current_business_id bigint NULL REFERENCES businesses_business (id) ON DELETE SET NULL
);

CREATE TABLE accounts_user_groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES accounts_user (id) ON DELETE CASCADE,
    group_id integer NOT NULL REFERENCES auth_group (id) ON DELETE CASCADE,
    UNIQUE (user_id, group_id)
);

CREATE TABLE accounts_user_user_permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES accounts_user (id) ON DELETE CASCADE,
    permission_id integer NOT NULL REFERENCES auth_permission (id) ON DELETE CASCADE,
    UNIQUE (user_id, permission_id)
);

CREATE TABLE accounts_invitation (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(254) NOT NULL,
    role varchar(20) NOT NULL,
    token uuid NOT NULL UNIQUE,
    status varchar(20) NOT NULL,
    expires_at timestamptz NOT NULL,
    accepted_at timestamptz NULL,
    created_at timestamptz NOT NULL,
    business_id bigint NOT NULL REFERENCES businesses_business (id) ON DELETE CASCADE,
    invited_by_id bigint NOT NULL REFERENCES accounts_user (id) ON DELETE CASCADE
);

CREATE TABLE accounts_businessmembership (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role varchar(20) NOT NULL,
    permissions jsonb NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    business_id bigint NOT NULL REFERENCES businesses_business (id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES accounts_user (id) ON DELETE CASCADE,
    UNIQUE (user_id, business_id)
);

CREATE TABLE clients_client (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    name varchar(200) NOT NULL,
    email varchar(254) NOT NULL,
    phone varchar(20) NOT NULL,
    secondary_phone varchar(20) NOT NULL,
    address text NOT NULL,
    city varchar(100) NOT NULL,
    notes text NOT NULL,
    is_active boolean NOT NULL,
    business_id bigint NOT NULL REFERENCES businesses_business (id) ON DELETE CASCADE
);

CREATE TABLE products_package (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    name varchar(200) NOT NULL,
    description text NOT NULL,
    base_price numeric(12, 2) NOT NULL,
    min_pax integer NOT NULL CHECK (min_pax >= 0),
    max_pax integer NULL CHECK (max_pax >= 0),
    price_per_additional_pax numeric(12, 2) NOT NULL,
    inclusions jsonb NOT NULL,
    image varchar(100) NULL,
    is_active boolean NOT NULL,
    business_id bigint NOT NULL REFERENCES businesses_business (id) ON DELETE CASCADE
);

CREATE TABLE products_product (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    name varchar(200) NOT NULL,
    description text NOT NULL,
    category varchar(50) NOT NULL,
    base_price numeric(12, 2) NOT NULL,
    unit varchar(50) NOT NULL,
    image varchar(100) NULL,
    is_active boolean NOT NULL,
    business_id bigint NOT NULL REFERENCES businesses_business (id) ON DELETE CASCADE
);

CREATE TABLE products_packageitem (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity integer NOT NULL CHECK (quantity >= 0),
    notes varchar(200) NOT NULL,
    package_id bigint NOT NULL REFERENCES products_package (id) ON DELETE CASCADE,
    product_id bigint NOT NULL REFERENCES products_product (id) ON DELETE CASCADE,
    UNIQUE (package_id, product_id)
);

CREATE TABLE bookings_booking (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    event_date date NOT NULL,
    event_time time NULL,
    event_end_time time NULL,
    venue varchar(500) NOT NULL,
    venue_address text NOT NULL,
    pax_count integer NOT NULL CHECK (pax_count >= 0),
    status varchar(20) NOT NULL,
    total_amount numeric(12, 2) NOT NULL,
    deposit_amount numeric(12, 2) NOT NULL,
    balance_amount numeric(12, 2) NOT NULL,
    notes text NOT NULL,
    special_requests text NOT NULL,
    business_id bigint NOT NULL REFERENCES businesses_business (id) ON DELETE CASCADE,
    client_id bigint NOT NULL REFERENCES clients_client (id) ON DELETE CASCADE,
    created_by_id bigint NULL REFERENCES accounts_user (id) ON DELETE SET NULL,
    package_id bigint NULL REFERENCES products_package (id) ON DELETE SET NULL
);

CREATE TABLE bookings_bookingreschedule (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    old_date date NOT NULL,
    old_time time NULL,
    new_date date NOT NULL,
    new_time time NULL,
    reason text NOT NULL,
    created_at timestamptz NOT NULL,
    approved_by_id bigint NULL REFERENCES accounts_user (id) ON DELETE SET NULL,
    booking_id bigint NOT NULL REFERENCES bookings_booking (id) ON DELETE CASCADE
);

CREATE TABLE contracts_contracttemplate (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    name varchar(200) NOT NULL,
    description text NOT NULL,
    content text NOT NULL,
    is_default boolean NOT NULL,
    is_active boolean NOT NULL,
    business_id bigint NOT NULL REFERENCES businesses_business (id) ON DELETE CASCADE
);

CREATE TABLE contracts_contract (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    rendered_content text NOT NULL,
    generated_file varchar(100) NULL,
    signed_file varchar(100) NULL,
    status varchar(20) NOT NULL,
    signed_at timestamptz NULL,
    signed_by varchar(200) NOT NULL,
    notes text NOT NULL,
    booking_id bigint NOT NULL REFERENCES bookings_booking (id) ON DELETE CASCADE,
    generated_by_id bigint NULL REFERENCES accounts_user (id) ON DELETE SET NULL,
    template_id bigint NULL REFERENCES contracts_contracttemplate (id) ON DELETE SET NULL
);

CREATE TABLE teams_teammember (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    name varchar(200) NOT NULL,
    email varchar(254) NOT NULL,
    phone varchar(20) NOT NULL,
    role varchar(100) NOT NULL,
    availability jsonb NOT NULL,
    hourly_rate numeric(10, 2) NULL,
    notes text NOT NULL,
    is_active boolean NOT NULL,
    business_id bigint NOT NULL REFERENCES businesses_business (id) ON DELETE CASCADE,
    user_id bigint NULL REFERENCES accounts_user (id) ON DELETE SET NULL
);

CREATE TABLE teams_bookingassignment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role varchar(100) NOT NULL,
    notes text NOT NULL,
    created_at timestamptz NOT NULL,
    assigned_by_id bigint NULL REFERENCES accounts_user (id) ON DELETE SET NULL,
    booking_id bigint NOT NULL REFERENCES bookings_booking (id) ON DELETE CASCADE,
    team_member_id bigint NOT NULL REFERENCES teams_teammember (id) ON DELETE CASCADE,
    UNIQUE (booking_id, team_member_id)
);

CREATE TABLE reminders_reminder (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    reminder_type varchar(20) NOT NULL,
    scheduled_at timestamptz NOT NULL,
    sent_at timestamptz NULL,
    status varchar(20) NOT NULL,
    subject varchar(200) NOT NULL,
    message text NOT NULL,
    recipient_email varchar(254) NOT NULL,
    recipient_phone varchar(20) NOT NULL,
    error_message text NOT NULL,
    retry_count integer NOT NULL CHECK (retry_count >= 0),
    booking_id bigint NOT NULL REFERENCES bookings_booking (id) ON DELETE CASCADE
);

CREATE TABLE reminders_remindertemplate (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200) NOT NULL,
    template_type varchar(50) NOT NULL,
    subject varchar(200) NOT NULL,
    content text NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    business_id bigint NOT NULL REFERENCES businesses_business (id) ON DELETE CASCADE,
    UNIQUE (business_id, template_type)
);

COMMIT;
